### ISSUE TITLE
Blinking border

### ISSUE THREAD

**Issue by loicfracheboud** [loicfracheboud/SigmaPi#19]
I just implement some code to test and work with camera and i found a bug.
The blinking border is not exaclty as expected..
![borderbug](https://cloud.githubusercontent.com/assets/18118871/14942712/bb84f972-0fc5-11e6-82e6-e481bb286372.jpg)

**Comment by loicgillioz** [comment]
Was always using the same _width_ distance, so i added size variation : 

``` java
//1:up, 2:right, 3:down, 4:left
float[] x = {width/2, width-thickness/2, width/2, thickness/2};
float[] y = {height-thickness/2, height/2, thickness/2, height/2};
float[] size = {width,height,width,height};
```

now it variates between _width_ and _height_, and then to draw it :

``` java
//rotation in degrees = i*90            
for(int i = 0; i < x.length; i++){
    g.drawFilledRectangle(x[i], y[i], size[i], thickness, i*90, frameColor);
}
```

**Comment by loicgillioz** [comment]
We must now use the real screen width and height, instead of the current camera view size... Added 2 variables in Param class to get height and width.

``` java
public static final int SCREEN_WIDTH = 1500;
public static final int SCREEN_HEIGHT = 900;
```
